name: multi-building-detector-gpu
channels:
- menpo
dependencies:
- opencv3=3.1.0
- python=3.5
- pip:
  - chainer==3.4.0
  - cupy==2.4.0
  - chainercv==0.8.0
  - pyyaml==3.12
  - matplotlib==2.1.0
  - scikit-learn==0.19.1
  - scipy==1.0.0
