input_dir: ../labeled_images/
test_dir: ../images_test/
output: result
batch_size: 1
train_split: 0.8
iterator: SerialIterator
pretrained_model: 'result/model'
save_trigger: 10000
train_split: 0.8
train_module: TripletTrainChain
model_module: multibuildingdetector.models.SSDTriplet

