input_dir: /Users/Fabian/Documents/HPI/Master/17WS/machineintelligence/repositories/labeled_images/
output: result
batch_size: 2
train_split: 0.8
iterator: SerialIterator
pretrained_model: 'result/model'
save_trigger: 10000
