input_dir: ../labeled_images/
test_dir: ../images_test/
output: result
batch_size: 32
iterator: SerialIterator
pretrained_model: 'result/model'
save_trigger: 10000
test_trigger: 1000
train_module: TripletTrainChain
model_module: multibuildingdetector.models.SSDTriplet

