input_dir: ../balanced_dataset_test_train/train/
test_dir: ../balanced_dataset_test_train/test/
output: result
batch_size: 32
iterator: MultiprocessIterator
device: 0
pretrained_model: 'result/model'
save_trigger: 10000
test_trigger: 1000
train_module: TripletTrainChain
model_module: multibuildingdetector.models.SSDTriplet
